version: '3.9'

services:
  mysql:
    image: mysql:8.0-bookworm
    restart: unless-stopped
    container_name: db_overwatch
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: nickFury123
      MYSQL_PASSWORD: nickFuryShield123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: